# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170422_1834'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('creator', 'question')]),
        ),
    ]
