# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170422_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='answer_detective',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='question_master',
            field=models.BooleanField(default=False),
        ),
    ]
