# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170423_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='game_room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.GameRoom'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set([('game_room', 'name')]),
        ),
    ]
