# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20170501_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='accepting_players',
            field=models.BooleanField(default=True),
        ),
    ]
